version: '3.8'

services:
  postgres_playground:
    container_name: postgres
    image: postgres
    # restart: unless-stopped
    environment:
      - POSTGRES_MULTIPLE_DATABASES=pubsdb,worlddb
      - POSTGRES_USER=playground
      - POSTGRES_PASSWORD=playground
    ports:
      - "5432:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - pgdata:/var/lib/postgresql/data/
      # copy the sql script to create tables
      #- ./postgresql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./postgresql:/docker-entrypoint-initdb.d
      - ./data:/home/data

  adminer_playground:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
        - 8080:8080
    depends_on:
        - postgres_playground

volumes:
  pgdata:
